package:
  create:
    max_package_size: "1000000000"
    set:
      # renovate: datasource=gitlab-tags depName=big-bang/bigbang versioning=semver registryUrl=https://repo1.dso.mil
      bigbang_version: "2.8.0"
      # should line up with the flux version in the BB release, see https://repo1.dso.mil/big-bang/bigbang/-/blob/master/base/flux/gotk-components.yaml#L3
      flux_version: "2.0.1"
      terraform_version: "1.4.2"
      terraform_provider_aws_version: 4.59.0
  deploy:
    set:
      # -- Name of the EKS cluster
      name_prefix: rex-ee18
      # -- AWS region
      region: us-gov-east-1
      # -- Name of existing Terraform state bucket
      state_bucket_name: rex-tfstate-backend20230426171358943300000001
      # -- Key path to Terraform state file within the bucket
      eks_state_key: pbme-dev/terraform.tfstate
      # -- Name of DynamoDB table used for Terraform state locking
      state_dynamodb_table_name: rex-tfstate-backend-lock-20230426171404
      iac_state_key: s3-loki/terraform.tfstate
      ephemeral: false
      kubernetes_service_account: logging-loki
      kubernetes_namespace: logging
      irsa_iam_role_name: logging-loki
      force_destroy: false
      create_kms_key: true
      irsa_policy_name: loki-irsa-policy
      # -- Bring your own kms key, if omitted a key will be created with an alias prefix of "<cluster name>-loki-"
      #loki_kms_key_arn: "arn:aws:kms:us-west-2:000000000000:key/mrk-0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a"
      # -- Bring your own kms key, if omitted a key will be created with an alias prefix of "<cluster name>-velero-"
      #velero_kms_key_arn: "arn:aws:kms:us-west-2:000000000000:key/mrk-0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a"
