name: Publish Zarf Package

on:
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Zarf Package
        uses: ./.github/actions/create-zarf-package

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Zarf Package
        run: zarf package publish zarf-package-*.tar.zst oci://ghcr.io/defenseunicorns/terraform-packages
        timeout-minutes: 60
