name: Tag and Publish Package

on:
  push:
    branches:
      - main

jobs:

  get-buildharness-software-versions:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      buildharness_version: ${{ steps.buildharness_software_versions.outputs.buildharness_version }}
      golang_version: ${{ steps.buildharness_software_versions.outputs.golang_version }}
      terraform_version: ${{ steps.buildharness_software_versions.outputs.terraform_version }}
      zarf_version: ${{ steps.buildharness_software_versions.outputs.zarf_version }}
    steps:
      - name: Get buildharness software versions
        id: buildharness_software_versions
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/get-buildharness-software-versions@main
        with:
          token: ${{ secrets.TOKEN }}
        
  tag-new-version:
    permissions: write-all
    runs-on: ubuntu-latest
    # Specify the Docker container image for the job
    outputs:
      release_created: ${{ steps.release-flag.outputs.release_created }}
    steps:
      - name: Create Release Tag
        id: tag
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest # use configs in release-please-config.json
      - id: release-flag
        run: echo "release_created=${{ steps.tag.outputs.release_created || false }}" >> $GITHUB_OUTPUT

  publish-package:
    needs: get-buildharness-software-versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Zarf Package
        uses: ./.github/actions/create-zarf-package

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish Zarf Package
      #   run: zarf package publish zarf-package-*.tar.zst oci://ghcr.io/defenseunicorns/terraform-packages
      #   timeout-minutes: 60
