name: Create Zarf Package
description: Creates a Zarf package for the requested path

runs:
  using: composite
  steps:
    - name: load build harness
      shell: bash -e -o pipefail {0}
      run: |
        zarf package create --confirm